spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/tryit
    username: sa
    password:
    driver-class-name: org.h2.Driver

  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create
      format_sql: true

logging:
  level:
    org.hibernate.SQL: debug